services:
  app:
    image: ghcr.io/florianzarbo/ecolle-scraper:latest
    environment:
        # Set this to your institution's base e-colle url
        - BASE_URL=https://ecolle.example.com
        # You need those to auth to ecolle and get your colle agenda
        - COLLES_USERNAME=YourUsername
        - COLLES_PASSWORD=YourPassword

        # Shows the n next colles
        - NUMBER_OF_COLLES_TO_SHOW=1

        # Set to your instance's url,
        # I recommend using https and setup either an already trusted ssl cert
        # or a self signed certificate (see below)
        # Default : https://ntfy.sh
        # - NTFY_SERVER=

        # Set this to the ntfy topic you want to use for your notifictions,
        # I suggest using a random string
        - NTFY_TOPIC=YourTopicName
        - NTFY_TITLE=Today's colles

        # Set to true if using a self signed certificate for your instance
        # Default : False
        # - SELF_SIGNED_CERTIFICATE=true

        # Path to your rootCA that signed you ssl certificate
        # - ROOT_CA_PATH=/app/certs/rootCA.pem
    # volumes:
      # - ./certs:/app/certs:ro