[project]
name = "ecolle-scraper"
version = "0.1.0"
description = "Scraper for ecolle"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
